# Generated by Django 4.2.2 on 2023-06-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autorage.car'),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='photo',
            field=models.ImageField(upload_to='autorage/media/cars'),
        ),
        migrations.AlterField(
            model_name='modulephoto',
            name='photo',
            field=models.ImageField(upload_to='autorage/media/modules'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='users'),
        ),
    ]
