# Generated by Django 4.2.2 on 2023-06-19 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorage', '0002_comment_car_alter_carphoto_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 19, 20, 13, 38, 836730)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='photo',
            field=models.ImageField(upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='modulephoto',
            name='photo',
            field=models.ImageField(upload_to='modules'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
