# Generated by Django 4.2.2 on 2023-06-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorage', '0003_car_pub_date_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='photo',
            field=models.ImageField(upload_to='cars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='modulephoto',
            name='photo',
            field=models.ImageField(upload_to='modules/%Y/%m/%d/'),
        ),
    ]
