# Generated by Django 4.2.2 on 2023-06-20 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorage', '0004_alter_carphoto_photo_alter_modulephoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=31)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='autor',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 20, 21, 52, 34, 95738)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='type',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='autorage.carbrand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='autorage.carmodel'),
        ),
    ]
