# Generated by Django 4.2.2 on 2023-08-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorage', '0008_alter_car_options_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulephoto',
            name='module',
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='autorage/static/images/rayan.jpg', upload_to='cars/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='photo',
            field=models.ImageField(default='autorage/static/images/rayan.jpg', upload_to='modules/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CarPhoto',
        ),
        migrations.DeleteModel(
            name='ModulePhoto',
        ),
    ]
